### ISSUE TITLE
ventoy: create start menu shortcut for VentoyVlnk.exe -s

### ISSUE THREAD

**Issue by candrapersada** [asheroto/ChocolateyPackages#9]
### Describe the feature or improvement you're requesting

The `ventoy` package should also create the `Ventoy Vlnk` start menu shortcut that points to `VentoyVlnk.exe -s`.

**Comment by asheroto** [comment]
Ah I see what you mean, not sure why we didn't do this before. I imagine most people would want to use `-s` simply to specify a directory, let alone a filename.

Also have added parameters so that users can disable the creation of desktop or Start Menu shortcuts. I will update the package description with this info.

Leaving the Issue open until the package is approved.

**Comment by asheroto** [comment]
I added the features to the package but I think we'll have to wait until the next package release to show up since version 1.0.97 is already approved. I'm double-checking with a colleague to see if we can push the revision through now. Wil report back.

The changes are reflected in the chocolateyinstall.ps1 file in ventoy\tools.

https://github.com/asheroto/ChocolateyPackages/tree/master/ventoy

**Comment by asheroto** [comment]
@candrapersada take a look at this.  Make sure to read the updated description.

https://community.chocolatey.org/packages/ventoy/1.0.97.20240126

Whatya think?

**Comment by candrapersada** [comment]
yes working and if possible add command line mode for Ventoy and VentoyVlnk
https://www.ventoy.net/en/doc_windows_cli.html
![gambar](https://github.com/asheroto/ChocolateyPackages/assets/36833664/0962c9b0-6e78-43c9-bc96-27ca505b6a9a)

**Comment by asheroto** [comment]
Are you thinking just a PowerShell window?

I'm hesitant to add any more icons because 3 is already quite a few. But maybe I could make it an option to add the icon.

**Comment by candrapersada** [comment]
> Are you thinking just a PowerShell window?

And for cmd windows

**Comment by asheroto** [comment]
Hmm.. I understand the idea but I don't think it's something that falls in the scope of the project. If it has it's own environment like `Developer PowerShell for VS 2022` then I might create a separate icon.

The package is now approved for use!

I appreciate your feedback. 😊
